### ISSUE TITLE
Listening on all interfaces causes a windows firewall prompt to pop up

### ISSUE THREAD

**Issue by Mossop** [mozilla/datomish-user-agent-service#5]
When the UAS starts windows pops up a firewall prompt that you have to accept or the UAS won't work. You can avoid this by only listening on the 127.0.0.1 interface.

**Comment by ncalexan** [comment]
Fixed by https://github.com/mozilla/datomish-user-agent-service/commit/b8626ef69a42584dcb0d299d36e33418c736d75a.
